'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System

Namespace DVLD_Project.Properties


    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    ''' </summary>
    ' This class was auto-generated by the StronglyTypedResourceBuilder
    ' class via a tool like ResGen or Visual Studio.
    ' To add or remove a member, edit your .ResX file then rerun ResGen
    ' with the /str option, or rebuild your VS project.
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class Resources

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
        End Sub

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DVLD_Project.Properties.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set(value As Global.System.Globalization.CultureInfo)
                resourceCulture = value
            End Set
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property AA As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AA", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_85_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-85-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_add_male_user_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-add-male-user-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_archive_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-archive-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_asking_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-asking-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_calendar_plus_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-calendar-plus-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_cancel_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-cancel-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_car_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-car-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_cloud_document_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-cloud-document-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_cloud_document_641 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-cloud-document-641", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_compose_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-compose-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_compose_641 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-compose-641", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_date_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-date-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_delete_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-delete-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_done_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-done-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_edit_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-edit-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_email_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-email-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_eye_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-eye-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_female_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-female-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_fingerprint_accepted_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-fingerprint-accepted-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_history_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-history-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_info_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-info-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_license_100 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-license-100", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_locked_outside_50 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-locked-outside-50", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_logout_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-logout-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_male_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-male-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_money_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-money-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_nation_100 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-nation-100", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_nation_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-nation-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_next_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-next-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_online_support_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-online-support-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_passport_100 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-passport-100", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_password_64__1_ As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-password-64 (1)", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_person_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-person-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_person_64__1_ As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-person-64 (1)", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_phone_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-phone-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_preview_file_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-preview-file-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_result_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-result-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_save_64__1_ As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-save-64 (1)", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_search_account_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-search-account-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_sent_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-sent-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_settings_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-settings-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_shipping_location_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-shipping-location-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_taxi_driver_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-taxi-driver-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_taxi_driver_641 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-taxi-driver-641", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_taxi_license_100 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-taxi-license-100", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_taxi_license_1001 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-taxi-license-1001", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_taxi_next_stop_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-taxi-next-stop-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_taxi_service_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-taxi-service-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_test_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-test-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_test_641 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-test-641", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_type_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-type-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_update_file_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-update-file-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_users_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-users-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_users_641 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-users-641", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_worldwide_location_64 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-worldwide-location-64", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property MobileCode__2_ As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MobileCode (2)", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
